### ISSUE TITLE
Deprecation message

### ISSUE THREAD

**Issue by MiyamotoAkira** [codurance/site#1622]
`Deprecation: posts.to_ary should be changed to posts.docs.to_ary.`

**Comment by sherlockq** [comment]
```
site_1  |        Deprecation: events.to_ary should be changed to events.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: posts.to_ary should be changed to posts.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: newsletters.to_ary should be changed to newsletters.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: podcasts.to_ary should be changed to podcasts.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: videos.to_ary should be changed to videos.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: events.to_ary should be changed to events.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
site_1  |        Deprecation: posts.to_ary should be changed to posts.docs.to_ary.
site_1  |                     Called by ["/usr/local/bundle/gems/jekyll-3.8.6/lib/jekyll/collection.rb:39:in `method_missing'"].
```

Not sure how is that from, I've checked the collection.rb file, it's not there:
```

    # Override of method_missing to check in @data for the key.
    def method_missing(method, *args, &blck)
      if docs.respond_to?(method.to_sym)
        Jekyll.logger.warn "Deprecation:",
          "#{label}.#{method} should be changed to #{label}.docs.#{method}."
        Jekyll.logger.warn "", "Called by #{caller(0..0)}."
        docs.public_send(method.to_sym, *args, &blck)
      else
        super
      end
    end
```

**Comment by sherlockq** [comment]
Probably it's from some 3rd party plugins. Not a easy ticket.

**Comment by MiyamotoAkira** [comment]
I believe in you

**Comment by sherlockq** [comment]
I tried. I failed. Sorry.
